### ISSUE TITLE
Chromium Error

### ISSUE THREAD

**Issue by malikcoskun** [GeKorm/dart-windows#13]
I got an error. Will I be able to fix the problem if I install Chromium? Thanks.

![screenshot](https://user-images.githubusercontent.com/37960679/45050172-4639c780-b089-11e8-8d9d-e906f0a27c7e.PNG)

**Comment by malikcoskun** [comment]
I guess 1.x.x. [I downloaded from here](https://github.com/GeKorm/dart-windows/releases/download/v1.x.x-f/Dart_x64.stable.setup.exe)

I switched from Windows 10 to Windows 7. I currently use it on Windows 7.

![capture](https://user-images.githubusercontent.com/37960679/45122060-7ce80e80-b16b-11e8-9bc4-6f3b0df972e9.PNG)

Thanks.

**Comment by GeKorm** [comment]
Thanks @malikcoskun I'm trying to reproduce the error. Could you follow these steps and let me know if you encounter any errors please?

1. Uninstall Dart from the control panel or provided uninstaller
2. Make sure you don't have the Dart SDK installed elsewhere
3. (Optional) Can you see Dart references in your PATH variable?
4. Download and install [this version](https://github.com/GeKorm/dart-windows/releases/download/v1.6.0/Dart_x64.stable.setup.exe)

Your help is greatly appreciated!

**Comment by GeKorm** [comment]
Fixed in 6cf11efe025b6aaa59c70f4eba80a97490bdb201 thanks for the very valuable bug report!
