### ISSUE TITLE
Update to v2.3?

### ISSUE THREAD

**Issue by ykmnkmi** [GeKorm/dart-windows#18]

**Comment by GeKorm** [comment]
@ykmnkmi Are you having trouble with the updater? It installs the latest version for me which is

**Stable** 2.2.0  
**Dev** 2.3.0-dev.0.1

You need the [Dev installer (second option)](http://www.gekorm.com/dart-windows/) for v2.3.0-dev.0.1

**Comment by ykmnkmi** [comment]
Sorry, i think it stable
