### ISSUE TITLE
32-bit Installer interest

### ISSUE THREAD

**Issue by GeKorm** [GeKorm/dart-windows#2]
If you are interested in an installer for the 32-bit Dart SDK, please leave a comment.

**Comment by ijneb** [comment]
I'm pretty late to this, but I'd like one

**Comment by GeKorm** [comment]
Hi @ijneb I'll try to get on this as soon as possible. I'll probably have something by Sunday, April 22. Would you be able to help me test it as I don't have a 32 bit installation around?

**Comment by GeKorm** [comment]
Is anyone able to test the 32 bit binaries?

**Comment by rhinck** [comment]
@GeKorm I am able to test them. Where are they located?

**Comment by GeKorm** [comment]
Installers available in the latest release :) https://github.com/GeKorm/dart-windows/releases/tag/v1.6.0
