### ISSUE TITLE
Where can I found the dartium?

### ISSUE THREAD

**Issue by liudonghua123** [GeKorm/dart-windows#22]
I download and install the dart-windows, but I couldn't found the dartium. Is this tool removed from the installer or I should install it myself.

![image](https://user-images.githubusercontent.com/2276718/75537773-8eedf900-5a52-11ea-9941-30393d5e657c.png)

**Comment by GeKorm** [comment]
Hi sorry for the late response, dartium is indeed deprecated https://dart.dev/dart-2#tools
