### ISSUE TITLE
Using installer behind proxy

### ISSUE THREAD

**Issue by alexmironof** [GeKorm/dart-windows#7]
Hi I cant install dart being behind a proxy, I've get timeout exception

**Comment by GeKorm** [comment]
Hi there, thanks for the bug report! I've tried a solution for this in the past #4 & #5 But both had issues with the download order. I'll give this another shot.

Can you please tell me if you're setting the proxy in windows, and if it's an authenticated proxy?

**Comment by alexmironof** [comment]
@GeKorm Thanks for the response! 
- It is authenticated proxy (I'm using `http://user:password@host:port/` as a proxy addres)
- It is set up by default by system administrator through windows registry inside `[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings]`

Also I'm using `ALL_PROXY`, `HTTP_PROXY` and `HTTPS_PROXY` enviroment variable for different software

**Comment by GeKorm** [comment]
This is really helpful info, I'll get started on this as soon as possible.

**Comment by alexmironof** [comment]
Thanks!

**Comment by GeKorm** [comment]
Hi, sorry for the delay. I have managed to make it work I'm just not sure if this UI is normally what you'd expect:
![image](https://user-images.githubusercontent.com/6104345/31355900-f42f0012-ad33-11e7-9371-5680b4a2bba8.png)
I'll release it in a bit, please let me know if you bump into problems or if the UI is strange.

**Comment by alexmironof** [comment]
@GeKorm Hi! Thanks for your great work! UI is really doesn't matter for me if it works as expected :sweat_smile:

**Comment by alexmironof** [comment]
I've tried new installer, but have no luck with it :worried: It says that download failed because operation  was terminated by timeout

**Comment by GeKorm** [comment]
Strange, I can see the files getting downloaded in the proxy logs and the setup completes fine.
If you don't mind, can check that you can indeed access these files using your proxy?  
 

https://storage.googleapis.com/dart-archive/channels/dev/release/latest/dartium/dartium-windows-ia32-release.zip  
https://storage.googleapis.com/dart-archive/channels/dev/release/latest/sdk/dartsdk-windows-x64-release.zip

I'll try to reproduce this with different proxy setups. I *do* still need to address the updater though, it doesn't do the version check through the proxy.

**Comment by alexmironof** [comment]
@GeKorm Yes I found this links inside source code and it downloads successfully, but after some timeout(about 30-60 seconds, because our proxy lags a bit)...

maybe there is default timeout for download operations wich is kind of smaller than my lags?

**Comment by GeKorm** [comment]
Ah yes that might be it! The default Windows timeouts are 60s for connect, 30s for send and receive. I'll try increasing that while playing around with a throttled connection. Thanks a lot for your feedback, it really helps!

**Comment by GeKorm** [comment]
I've released the latest version with 90 second timeouts, plus made the Updater not ignore the proxy https://github.com/GeKorm/dart-windows/releases/tag/v1.4.1

Let me know if you still run into timeouts or other issues. Thanks for your patience :)

**Comment by alexmironof** [comment]
@GeKorm thankd a lot! I will be able to test it at friday

**Comment by alexmironof** [comment]
@GeKorm now it works as expected, thanks!
