### ISSUE TITLE
Please display the exact version for both stable and dev installers

### ISSUE THREAD

**Issue by rootext** [GeKorm/dart-windows#8]

**Comment by GeKorm** [comment]
Done in 443037d5e4e23ed6dabb6699a64a02cffd3b38b0  
Will put up a release tomorrow after testing on a few more PCs.  
Thanks for the great suggestion!

**Comment by GeKorm** [comment]
Released https://github.com/GeKorm/dart-windows/releases/tag/v1.4.1
